export enum BUS_SIDEBAR {
  RENAME = "SIDEBAR::RENAME",
  SWITCH_SETTING = "SIDEBAR::SWITCH_SETTING",
}

export enum BUS_EDITOR {
  SYNC_TOC = "EDITOR::SYNC_TOC",
  SYNC_IMGLIST = "EDITOR::SYNC_IMGLIST",
  SYNC_VIEW = "EDITOR::SYNC_VIEW",
  CLOSE_FILE = "EDITOR::CLOSE_FILE",
  REVEAL_SECTION = "EDITOR::REVEAL_SECTION",
  SWITCH_SECTION = "EDITOR::SWITCH_SECTION",
}
