export enum BUS_FILE {
  OPEN_FILE = "OPEN_FILE",
  CLOSE_FILE = "CLOSE_FILE",
}

export enum BUS_TOC {
  SYNC_TOC = "SYNC_TOC",
  REVEAL_SECTION = "REVEAL_SECTION",
  SWITCH_SECTION = "SWITCH_SECTION",
}

export enum BUS_UI {
  SYNC_RESIZE = "SYNC_RESIZE",
  SAVE_RESIZE = "SAVE_RESIZE",
}
